### ISSUE TITLE
Detail about Changes

### ISSUE THREAD

**Issue by Yilliee** [IcemanDev/android_device_samsung_klte#1]
Hello,
I'm sorry for writing this as an issue but I couldn't find any other way to reach out to you.

Can you explain how you managed to fix aroma on klte?

I got the files in root/sbin and the kernel merged with the official twrp and ofox but I also want to apply the aroma fix to ks01lte (S4 LTE+). So, can you please explain a bit about what you did or any other way I can contact you?

**Comment by IcemanDev** [comment]
I had developed the kernel (zImage) with flavor specifications.

Il giorno lun 21 dic 2020 alle ore 08:03 Yillie <notifications@github.com>
ha scritto:

**Comment by Yilliee** [comment]
Can you like explain what you mean by "flavored specifications" or point me to a guide or a repository which I can use as a referance for fixing aroma on ks01lte?

**Comment by IcemanDev** [comment]
Sorry, it was an old project and I deleted the clipboard.

Il giorno lun 21 dic 2020 alle ore 08:52 Yillie <notifications@github.com>
ha scritto:

**Comment by Yilliee** [comment]
Ok n.p. thnx for your time.
